In [2]:
%run myimport.py


import Image numpy->np matplotlib->plt pandas->pd tushare->ts base64 pytesseract->pt success!


In [4]:
data = np.arange(6).reshape(2,3)

In [19]:
data

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1


array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [23]:
data2 = [[1, 2, 3, 4, 5, 6], [1.1, 2.2, 3.3, 4.4, 5.5, 6.6]]
arr2 = np.array(data2)
arr2

array([[ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ],
       [ 1.1,  2.2,  3.3,  4.4,  5.5,  6.6]])

In [26]:
arr2.ndim

2

In [28]:
arr2.shape

(2, 6)

In [29]:
arr2.dtype

dtype('float64')

In [32]:
np.zeros(10)
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [35]:
np.ones(10)
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [38]:
np.empty((2, 3, 2))

array([[[ 1. ,  2. ],
        [ 3. ,  4. ],
        [ 5. ,  6. ]],

       [[ 1.1,  2.2],
        [ 3.3,  4.4],
        [ 5.5,  6.6]]])

In [40]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
np.eye(3,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [45]:
np.identity(3
           )

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [48]:
arr3 = np.array([1, 2, 3], dtype = np.float64)
arr3

array([ 1.,  2.,  3.])

In [50]:
arr4 = np.array([1, 2, 3], dtype = np.int32)
arr4

array([1, 2, 3], dtype=int32)

In [53]:
arr4.dtype

dtype('int32')

In [56]:
#强制类型转换 int8-->float64
float_arr = arr4.astype(np.float64)
float_arr

array([ 1.,  2.,  3.])

In [60]:
#float64-->int8
int_arr = arr3.astype(np.int8)
int_arr


array([1, 2, 3], dtype=int8)

In [76]:
#numric string-->int8
numric_strings = np.array(['1', '-9', '99999'], dtype=np.string_)
numric_strings.astype(int)


array([    1,    -9, 99999])

In [79]:
#dtype函数做类型转换 int-->float
int_array = np.arange(10)
calibers = np.array([.11, .22, .33, .44, .55, .66], dtype=np.float64)
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [81]:
#dtype类型简写: u4=uint32
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [89]:
#数组和标量运算
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [90]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [91]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [93]:
1 / arr 

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [95]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [98]:
#基本的索引和切片
#--一维数组操作
arr01 = np.arange(10)
arr01

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
arr01[5]

5

In [103]:
arr01[5:8]

array([5, 6, 7])

In [105]:
arr01[5:8] = 12
arr01

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [107]:
#数组切片操作,对切面的操作是直接修改原数组
arr01_slice = arr01[5:8]
arr01_slice[1] = 12345
arr01

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [111]:
arr01_slice[:] = 99
arr01

array([ 0,  1,  2,  3,  4, 99, 99, 99,  8,  9])

In [114]:
#如果要得到数组的一个副本而非视图，就需要显式的进行复制操作，如下
arr01_slice02 = arr01[5:8].copy()
arr01_slice02[:] = 100
arr01
arr01_slice02

array([100, 100, 100])

In [118]:
#二维数组操作
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2] #选取数组的一行

array([7, 8, 9])

In [121]:
#选取数组里一个元素的两种表示方法
arr2d[0][2]
arr2d[0, 2]

3

In [130]:
#三维数组操作 2*2*3
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [131]:
#arr3d[0]是一个2*3的数组
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
old_values = arr3d[0].copy()
arr3d[0] = 66
arr3d

array([[[66, 66, 66],
        [66, 66, 66]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [135]:
arr3d[0] = old_values
old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [137]:
arr3d[1, 0] 

array([7, 8, 9])

In [139]:
#切片和索引操作
#一维数组切片
arr01[1:6]

array([ 1,  2,  3,  4, 99])

In [148]:
#二维数组切片
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [147]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [144]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [149]:
arr2d[1, :2]

array([4, 5])

In [151]:
arr2d[2, :1]

array([7])

In [158]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [160]:
#切片赋值操作
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [174]:
#布尔型索引操作 布尔型选取数组数据时，都是创建数据副本的，非视图方式。
names = np.array(['hjzheng', 'yytian', 'kiky', 'xinxin', 'xuanxuan', 'baba', 'mama'])
data = np.random.randn(7,4)
names

array(['hjzheng', 'yytian', 'kiky', 'xinxin', 'xuanxuan', 'baba', 'mama'],
      dtype='|S8')

In [175]:
data

array([[ 0.466376  , -1.58354507,  1.2170833 ,  0.30759242],
       [ 1.60482731,  0.10270288, -0.38491604,  0.27185565],
       [-0.30540787, -1.54416343, -0.75499219,  0.41049175],
       [ 0.19333215,  0.14404027,  0.38810895, -1.564317  ],
       [ 1.51915071,  1.22323939, -1.5485844 , -0.32323651],
       [ 1.90279842, -0.76427563, -1.08395563, -0.56576652],
       [-1.01427291, -0.15355949, -0.1739316 , -0.05258145]])

In [176]:
names == 'hjzheng'

array([ True, False, False, False, False, False, False], dtype=bool)

In [181]:
data[names == 'hjzheng']

array([[ 0.466376  , -1.58354507,  1.2170833 ,  0.30759242]])

In [182]:
data[names == 'hjzheng', 2:]

array([[ 1.2170833 ,  0.30759242]])

In [183]:
data[names == 'hjzheng', 3]

array([ 0.30759242])

In [185]:
names != 'hjzheng'

array([False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [188]:
data[~(names == 'hjzheng')]

array([[ 1.60482731,  0.10270288, -0.38491604,  0.27185565],
       [-0.30540787, -1.54416343, -0.75499219,  0.41049175],
       [ 0.19333215,  0.14404027,  0.38810895, -1.564317  ],
       [ 1.51915071,  1.22323939, -1.5485844 , -0.32323651],
       [ 1.90279842, -0.76427563, -1.08395563, -0.56576652],
       [-1.01427291, -0.15355949, -0.1739316 , -0.05258145]])

In [190]:
mask = (names == 'hjzheng') | (names == 'yytian')
mask

array([ True,  True, False, False, False, False, False], dtype=bool)

In [192]:
data[mask]

array([[ 0.466376  , -1.58354507,  1.2170833 ,  0.30759242],
       [ 1.60482731,  0.10270288, -0.38491604,  0.27185565]])

In [194]:
#将data里的所有负值元素都设置为0
data[data < 0] =0
data

array([[ 0.466376  ,  0.        ,  1.2170833 ,  0.30759242],
       [ 1.60482731,  0.10270288,  0.        ,  0.27185565],
       [ 0.        ,  0.        ,  0.        ,  0.41049175],
       [ 0.19333215,  0.14404027,  0.38810895,  0.        ],
       [ 1.51915071,  1.22323939,  0.        ,  0.        ],
       [ 1.90279842,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [196]:
data[names != 'hjzheng'] = 9
data

array([[ 0.466376  ,  0.        ,  1.2170833 ,  0.30759242],
       [ 9.        ,  9.        ,  9.        ,  9.        ],
       [ 9.        ,  9.        ,  9.        ,  9.        ],
       [ 9.        ,  9.        ,  9.        ,  9.        ],
       [ 9.        ,  9.        ,  9.        ,  9.        ],
       [ 9.        ,  9.        ,  9.        ,  9.        ],
       [ 9.        ,  9.        ,  9.        ,  9.        ]])

In [199]:
#花式索引 Fancy indexing
arrF = np.empty((8, 4))
for i in range(8):
    arrF[i] = i
arrF

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [201]:
#选取固定的几行数据
arrF[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [205]:
arr02 = np.arange(32).reshape((8, 4))
arr02

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [207]:
arr02[[1, 5, 7, 2], [0, 3, 1, 2]]


array([ 4, 23, 29, 10])

In [211]:
arr02[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [212]:
#np.ix_函数用法示例
arr02[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])